### PR TITLE
Community original

### LINKED ISSUE #43: Issue with view data model with multiple projects
[Test1.zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/2476577/Test1.zip)

If we have multiple projects where the derived DbContext have the same name, then attempting to view the data model fails if
1) view data model in project 1
2) attempt to view data model in project 2

We get 'this file has been modified outside the editor. Do you want to reload it?'
If we select yes then we get 'The file blah.edmx can be saved...'

The generated edmx probably needs to be <project name>.<context name>.edmx.

Just noticed this also happens if the contexts are in different solutions.

### PR DESCRIPTION
**Pull request by PhilPJL**
- Fixed #43 by creating the .edmx in a sub-folder of the temp folder. The sub-folder name is now the project guid instead of a random string.
- Changed the name of the .edmx to be the context type 'FullName'. This makes it easier to see which EDML is which, when there are several open.
- If the .edmx is open and the user generates it again, close the open one to eliminate the annoying warning dialogs.
- Set the current directory to the project build output folder. This fixes an issue when there are contexts in multiple projects which have references to other projects.

### CODE REVIEW

File: src/PowerTools/Handlers/ViewContextHandler.cs [hunk 1]
```diff
@@ -30,33 +31,55 @@ public void ViewContext(MenuCommand menuCommand, dynamic context, Type systemCon
...
+                        : FileExtensions.Xml);
 
                 if (File.Exists(filePath))
                 {
                     File.SetAttributes(filePath, FileAttributes.Normal);
+
+                    // Close the file if already open to eliminate warning dialogs
+                    if (_package.DTE2.ItemOperations.IsFileOpen(filePath))
+                    {
+                        var openDocuments = _package.DTE2.Documents
```
Comment (ErikEJ) [inline src/PowerTools/Handlers/ViewContextHandler.cs]: Will this not close all open documents?

**Comment by ErikEJ** [comment]
Looks good, have a couple of questions

File: src/PowerTools/PowerTools.csproj [hunk 2]
```diff
@@ -61,6 +61,7 @@
     <Reference Include="System.Data.Entity" />
     <Reference Include="System.Data.Entity.Design" />
     <Reference Include="System.Design" />
+    <Reference Include="System.Drawing" />
```
[the remark this answers is not in the document]
Comment (PhilPJL) [reply src/PowerTools/PowerTools.csproj]: I removed this reference by mistake on my previous pull request.  System.Drawing is referenced in VSPackage.resx.

File: src/PowerTools/Handlers/ViewContextHandler.cs (hunk 1 above)
Comment (PhilPJL) [reply src/PowerTools/Handlers/ViewContextHandler.cs]: No just the one.  Check the where clause

```
.Where(d => 
        { 
             VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(); 
             **return d.FullName == filePath;** 
        }) 
        .ToList();
```

It would have read ` .Where(d => d.FullName == filePath)` if it wasn't for that assertion.

**Comment by ErikEJ** [comment]
Thanks for the contribution!
